### ISSUE TITLE
Sending Love

### ISSUE THREAD

**Issue by efemeryds** [Toumash/hearty#12]
As a paired user, i can click the heart, so the app will send a notification with my message to my loved one

## Acceptance Criteria:

 - [x] [The system will remember your session, so you wont have to login or remember strange codes](https://github.com/Toumash/hearty/pull/18)
 - [x] This screen should inform the user, that the system recognizes him as a user
 - [x] User has to know if the loved one accepted the invitation

Linked: 
- Invitation is to be sent by https://github.com/Toumash/hearty/issues/17

Work:
- [x] backend
- [x] frontened

**Comment by efemeryds** [comment]
To split into link generation and status + sending a notification

**Comment by Toumash** [comment]
> To split into link generation and status + sending a notification

Link generation: https://github.com/Toumash/hearty/issues/17

**Comment by Toumash** [comment]
Backend for love sending done! https://github.com/Toumash/hearty/pull/23
