### ISSUE TITLE
Receive Love

### ISSUE THREAD

**Issue by efemeryds** [Toumash/hearty#14]
As a paired user, when receiving love, i would like to click a notification from my loved one, so i can see their message

## Acceptance criteria
 - [x] Notification design [choose which one to use](https://web-push-book.gauntface.com/demos/notification-examples/)
 - [x] Love page  (opened by clicking notification)

**Comment by Toumash** [comment]
There will be one problem with a notification. Currently it wont have a message from the user - https://github.com/Toumash/hearty/issues/19
